### ISSUE TITLE
error on drag n drop

### ISSUE THREAD

**Issue by dreed47** [cgaspard/mantiskanban#9]
When dragging an issue from one column to another I get the following error.  I suspect it might have something to do with custom fields I have

---

Error Updating: Error: Error Type: SYSTEM NOTICE,
Error Description:
Undefined index:  field,
Stack Trace:
mc_api.php L160 mc_error_handler()
mc_issue_api.php L836 mci_issue_set_custom_fields()
nusoap.php L4087 mc_issue_update()
nusoap.php L4087 call_user_func_array()
nusoap.php L3718 invoke_method()
mantisconnect.php L1717 service()
mantisconnect.php L0 {main}()

**Comment by jrotondo-madaket** [comment]
I'm seeing this error with the latest version of Mantis (1.2.19) and MantisKanban (latest commit 595e5eb17b). Anything I can do about it?

**Comment by cgaspard** [comment]
I haven't been able to recreate the error, so I don't have a clue how to fix it.

Do you have any debug information from Chrome?   Any errors in the chrome error log?

**Comment by jrotondo-madaket** [comment]
Yes. There are errors:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
index.js:361 SelectProject() called.
kanban.js:168 Uncaught TypeError: Cannot read property 'Element' of nullKanban.AddGlowToRelatedStories @ kanban.js:168onmouseover @ (index):1
kanban.js:177 Uncaught TypeError: Cannot read property 'Element' of nullKanban.RemoveGlowToRelatedStories @ kanban.js:177onmouseout @ (index):1
kanban.js:250 DragStart1
kanban.js:255 DragStart2
kanban.js:259 DragEnd1
kanban.js:262 DragEnd1
soapclient.js:197 POST http://mantisdomainname.com/api/soap/mantisconnect.php 500 (Internal Server Error)SOAPClient._sendSoapRequest @ soapclient.js:197SOAPClient._loadWsdl @ soapclient.js:139SOAPClient.invoke @ soapclient.js:125Mantis.IssueUpdate @ mantis.js:626UpdateListForCanbanStory @ kanban.js:426Drop @ kanban.js:301
kanban.js:336 UpdateKanbanStoryComplete Error: Error Type: SYSTEM NOTICE,
Error Description: Undefined index: field

Thanks,
John

**Comment by jrotondo-madaket** [comment]
After a bit more testing, I can also confirm that the error happens whether you are using the default states or add a custom ScrumBucket field to map stories into custom buckets. Let me know if you need more info. I'd actually be willing to do a join.me with you if it would help to get this resolved.

**Comment by jrotondo-madaket** [comment]
I currently have 3 custom fields (Code Review Status [list], Environment [list], and Iteration [numeric]).

**Comment by cgaspard** [comment]
Do you have parent / child relationships between the issues you are working with?    I ask because the code that is erroring for you is related to that.   The Kanban highlights parent and child issues when it detects them.

**Comment by jrotondo-madaket** [comment]
I'll dig it up for you!

**Comment by jrotondo-madaket** [comment]
Grabbed a fresh error log:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
index.js:361 SelectProject() called.
index.js:361 SelectProject() called.
index.js:499 Done Loading 68
kanban.js:250 DragStart1
kanban.js:255 DragStart2
kanban.js:259 DragEnd1
kanban.js:262 DragEnd1
soapclient.js:197 POST http://bugs.madakethealth.com/api/soap/mantisconnect.php 500 (Internal Server Error)SOAPClient._sendSoapRequest @ soapclient.js:197SOAPClient._loadWsdl @ soapclient.js:139SOAPClient.invoke @ soapclient.js:125Mantis.IssueUpdate @ mantis.js:626UpdateListForCanbanStory @ kanban.js:426Drop @ kanban.js:301
kanban.js:336 UpdateKanbanStoryComplete Error: Error Type: SYSTEM NOTICE,
Error Description: Undefined index: field

These are the tickets currently within the view that exhibits this error:
1572 - no relationships
1571 - no relationships
1538 - parent of 1543
1573 - related to 1543
1561 - child of 1552 (completed and not in this filtered view)
1567 - no relationships
1568 - no relationships
1541 - no relationships
1539 - no relationships
1540 - no relationships
1581 - no relationships

**Comment by jrotondo-madaket** [comment]
Perhaps that relationship to the item not in this view is to blame, since it cannot highlight an element that isn't in the DOM?

**Comment by jrotondo-madaket** [comment]
Shall I assume that having these kinds of relationships across our tickets is unsupported by MantisKanban?

**Comment by cgaspard** [comment]
Is the relationships between issues on separate projects?   That is most likely the problem.    Haven’t had a chance to really get in and debug the scenario,  but I think that is probably it.

Corey
On May 15, 2015 at 11:40:15 AM, John Rotondo (notifications@github.com) wrote:

Shall I assume that having these kinds of relationships across our tickets is unsupported by MantisKanban?

**Comment by jrotondo-madaket** [comment]
According to Mantis, they are set to the same project, unfortunately.
